version: '3.8'

services:
  ball-detection-api:
    build: ./ai_api/
    ports:
      - "8000:8000"
    volumes:
      - ./ai_api/models:/app/models
    environment:
      - MODEL_PATH=/app/models/best.pt
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3